Initial implementation
bluemarblepayroll/burner pull request #1
Opened 2020-10-14 05:37 UTC by mattruggio

This PR contains the first implementation for the Burner library.  At its core its pretty basic, it provides:

1. a way to object-model jobs using a configuration/data-first approach
2. a way to declare ordering/reusing of jobs (steps)
3. a basic/core job library (i.e. sleep, read, write, etc.)

2020-10-21 18:44 UTC, mattruggio commented on lib/burner/pipeline.rb
> +      end
Rspec is altering this due to an expected message reception expectation. in cli_spec.  I am sure there is a way around this by changing implementation.

2020-10-21 20:00 UTC, mattruggio commented on lib/burner/jobs/collection/arrays_to_objects.rb
> +          payload.value = (payload.value || []).map { |array| index_to_key_map(array) }
This gets funkadelic when dealing with Hash objects, since Hash responds to #to_a.  I am going to create an intermediary helper to deal with this nuance for jobs which value should be an array but also honor Hash objects.

2020-10-21 20:03 UTC, mattruggio commented on lib/burner/jobs/collection/transform/attribute.rb
> +        class Attribute
I agree.

2020-10-21 20:38 UTC, mattruggio commented on lib/burner/jobs/io/exist.rb
> +          short_circuit && !exists ? false : nil
That is technically what is happening: nil is treated as "true".  Basically anything that is not explicitly FalseClass is considered truthy, while only FalseClass would halt execution.

2020-10-21 20:39 UTC, mattruggio commented on lib/burner/jobs/io/read.rb
> +        def initialize(name:, path:, binary: false)
Oh, its severely lacking in customization and functionality.  This is really just meant to serve as a base.

2020-10-21 21:15 UTC, mattruggio commented on lib/burner/payload.rb
> +      written_files: []
Jobs can technically do anything they want.  This was just a way to keep track of all the writes to the file system.  This does feel very consumer/application centric and not something that is a concern for this library (in a concrete form.). I am going to think about, instead, providing a file system observer type mechanic so applications can plug this in if necessary.

2020-10-21 21:17 UTC, mattruggio commented on lib/burner/jobs/collection/arrays_to_objects.rb
> +          @mappings = Modeling::KeyIndexMapping.array(mappings)
I think this is subjective.  Technically, if this job was specified with no mappings, it would return an array with N number of entries, with each entry being an empty object.  IMHO, this is deemed acceptable and is up to the consumer to not use it in this way.  Let me know if you really feel strongly about this.

2020-10-22 14:01 UTC, mattruggio commented on lib/burner/payload.rb
> +      written_files: []
I re-defined this as "side_effects" as a place for jobs to store structured output that is outside the payload#value main result.

2020-10-22 16:37 UTC, mattruggio commented
Thanks @gerryster for all the feedback, everything should be addressed and ready for a re-review.  Major changes since the PR was initially reviewed:

1. Remove class nesting with Jobs.  Currently it was module -> class -> module -> class.  This replaces `class Jobs` with `module Library` and smooths out the namespacing to: module -> module -> module -> class.
2. Payload#written_files now becomes a more generic Payload#side_effects.
3. Some classes moved into Modeling instead of nesting inside job classes.  This helps minimize lengthy fully qualified namespaces.

2020-10-23 21:43 UTC, gerryster commented on lib/burner/jobs/collection/arrays_to_objects.rb
> +          @mappings = Modeling::KeyIndexMapping.array(mappings)
Ok, that works for me as long as there is a base case for nil.

2020-10-23 21:50 UTC, gerryster commented on lib/burner/jobs/io/exist.rb
> +          short_circuit && !exists ? false : nil
Yea, that is what is tripping me up. Treating nil as true is messing with the way I think about truthy and falsey especially in Ruby where literal false and nil are the ONLY two values which are falsey.

Taking a step back...instead of tying the halting behavior to the return code of perform, what if there was an explicit "halt" method that had to be called in order to halt the pipeline? I have seen this approach in the past but I can't cite exactly where I first saw it. Apparently Sinatra uses this approach to halt the execution of a request: https://www.rubydoc.info/gems/sinatra/Sinatra%2FBase:halt .

2020-10-23 22:02 UTC, gerryster commented on lib/burner/jobs/io/exist.rb
> +          short_circuit && !exists ? false : nil
More thoughts on the halt method approach...if pipeline were available to jobs then this could be `pipeline.halt` which makes it pretty clear what is going on. It does couple the objects together a little more directly though. I suppose the direct halt method would prevent that coupling.

2020-10-26 01:03 UTC, mattruggio commented on lib/burner/jobs/io/exist.rb
> +          short_circuit && !exists ? false : nil
I have used that pattern before in libraries that provide lifecycle management, let me try and remove the direct use of #perform's return and instead opt for another method.  I think I will try and keep the pipeline out of jobs (for now), and keep it job-level.  I can see clear pro's and con's with exposing the pipeline instance to jobs.  Basically it would pass in self into each job, giving each job a reference, but I am going to try and not cross that bridge (for now.)

2020-10-27 17:32 UTC, gerryster requested changes
Ok @mattruggio: I have reviewed up to and including c2550a7ecac676babca85873edaec0247988e04e . So far this is looking good. My comments are all pretty minor. I like the side effects notion for files.

One thing that I have been pondering is regarding the payload object. What do you think about having more explicit input and output channels instead of the current "value" attribute which currently serves both purposes? Some of the documentation you added about how jobs deal with input and output are reinforcing this idea in my mind.

2020-10-27 17:40 UTC, mattruggio commented on lib/burner/payload.rb
> +                :time
It is not technically "created at", it is merely a way to give all the jobs a common "time" instead of relying on relative and always moving Time.now.  This way jobs/pipelines can be more easily replayed, if implemented using the time input.

2020-10-27 17:41 UTC, mattruggio commented on lib/burner/side_effects/written_file.rb
> +      def initialize(logical_filename:, physical_filename:, time_in_seconds:)
I feel like this is redundant, as the class is named WrittenFile.

2020-10-27 17:49 UTC, mattruggio commented on lib/burner/library/dummy.rb
>      class Dummy < Job
I am going to rename this to `Nothing`

2020-11-02 16:05 UTC, mattruggio commented
@gerryster - All feedback should be accounted for.  Let me know how the next round of review goes.

2020-11-03 19:25 UTC, gerryster commented on lib/burner/job_with_register.rb
> +    def initialize(name:, register: '')
What do you think about being a little more explicit about the "default" register. So instead of the default being the empty string, it could be a constant defined in this class. Something like this:

```ruby
module Burner
    class JobWithRegister < Job
      attr_reader :register
  
      DEFAULT_REGISTER = 'default'
      
      def initialize(name:, register: DEFAULT_REGISTER)
      ...

2020-11-03 20:36 UTC, gerryster requested changes
Back to you @mattruggio. This is looking good. All of my comments are very minor.

2020-11-03 20:36 UTC, gerryster commented on README.md
> +* If you see that a job accepts a 'register' attribute/argument, that indicates a job will access and/or mutate the payload.  The register indicates which part of the payload the job will interact wi
Can you add another note explaining the "b" namespace for these jobs?

2020-11-04 19:43 UTC, mattruggio commented on lib/burner/job_with_register.rb
> +    def initialize(name:, register: '')
I like this.  I needed to consolidate the magic '' string anyways.

2020-11-04 21:25 UTC, mattruggio commented on lib/burner/modeling/validations/blank.rb
> +          resolver.get(object, key).to_s.empty?
Yes!  Good catch.

2020-11-04 22:45 UTC, gerryster commented on lib/burner/modeling/validations/present.rb
> +      class Present < Blank
Good call on reusing blank! I almost suggested that initially.

2020-11-04 22:47 UTC, gerryster approved these changes
LGTM!

2020-11-05 11:52 UTC, merged