Add key mappings to b/collection/flat_file_parse. Added b/collection/unshift job.
bluemarblepayroll/burner pull request #15
Opened 2021-08-06 18:52 UTC by johnbos

In this PR, b\collection\flat_file_parse was updated to allow a key_mappings array be specified. If key mappings are defined, only those keys that are mapped and exist in the register payload will be added to the keys_register. This will allow keys to be more flexible to allow other downstream jobs that expect certain keys to exist. Key mappings are not required and if not defined b\collection\flat_file_parse works like it does currently.

Also in this PR, a new job was added: b\collection\unshift. This new job takes in an array of from_register names and adds the values of those registers to the beginning of the to_register's array. This will move all existing elements in the to_register upward. An alias for b\collection\unshift was defined as well called b\collection\prepend.

2021-08-09 21:59 UTC, mattruggio commented on lib/burner/library/collection/flat_file_parse.rb
> +          mapped_keys.each do |mapped_key_hash|
Form nitpicks:

You can use #each_with_object instead of explicitly declaring keys and returning keys, something like this:

````ruby
mapped_keys.each_with_object([]) do |mapped_key_hash, memo|
  mapped_key = mapped_key_hash[:mapped_key_name]

  memo << mapped_key if mapped_key
end
````

I also chose the shovel op. over the #push method (should be the same thing)

2021-08-09 21:59 UTC, mattruggio commented on lib/burner/library/collection/flat_file_parse.rb
> +          keys.each do |key|
Same thing here, I would opt for #each_with_object over explicit local variable

2021-08-09 21:59 UTC, mattruggio commented on lib/burner/library/collection/flat_file_parse.rb
> +            key_hashes.push(key_hash)
super nitpick: opt for shovel operator over #push method.

2021-08-09 22:00 UTC, mattruggio commented on lib/burner/library/collection/flat_file_parse.rb
> +          keys.each do |key|
same thing here as well, #each_with_object and shovel op.

2021-08-09 22:01 UTC, mattruggio commented on lib/burner/library/collection/unshift.rb
> +      class Unshift < JobWithRegister
JobWithRegister utilizes a register instance variable, not to_register so I am not sure this quite conforms to what a subclass of JobWithRegister would be.  I suggest either renaming to_register to register or changing its parent to just Job.

2021-08-09 22:03 UTC, mattruggio commented on lib/burner/library/collection/unshift.rb
> +            register.unshift(from_register_value)
It is important to note that this job is mutable _on_ the from_registers, not just the to_register.  Personally I would attempt to keep from mutating the from_registers and just preprend the from_register objects onto the (to_)register (instead of a hard unshift over and over).

2021-08-09 22:05 UTC, mattruggio commented
I left some comments on both form and function.  What sticks out:

1. Opt for #each_with_object expressive syntax over explicit procedural variable use.
2. Opt for shovel (<<) operator over Array#push calls
3. Conform to JobWithRegister or change the parent for the Unshift class.
4. Double-check that mutating the from registers is the desired functionality.  Personally, I am against this as I would like things as immutable as possible, when possible, but this _is_ valid implementation/functionality if its what is called for.

Back to you #johnbos

2021-08-09 22:07 UTC, mattruggio requested changes
I left some comments on both form and function. What sticks out:

Opt for #each_with_object expressive syntax over explicit procedural variable use.
Opt for shovel (<<) operator over Array#push calls
Conform to JobWithRegister or change the parent for the Unshift class.
Double-check that mutating the from registers is the desired functionality. Personally, I am against this as I would like things as immutable as possible, when possible, but this is valid implementation/functionality if its what is called for.

Back to you #johnbos

2021-08-11 14:30 UTC, johnbos commented on lib/burner/library/collection/flat_file_parse.rb
> +        def update_keys_using_mappings(keys, output)
Updated code.

2021-08-11 14:32 UTC, johnbos commented on lib/burner/library/collection/flat_file_parse.rb
> +          keys.each do |key|
Update code from feedback.

2021-08-11 14:32 UTC, johnbos commented on lib/burner/library/collection/flat_file_parse.rb
> +            key_hashes.push(key_hash)
Updated code.

2021-08-11 14:33 UTC, johnbos commented on lib/burner/library/collection/flat_file_parse.rb
> +          keys.each do |key|
Updated code.

2021-08-11 14:33 UTC, johnbos commented on lib/burner/library/collection/unshift.rb
> +      class Unshift < JobWithRegister
Updated, renamed "to_register" to "register".

2021-08-12 03:43 UTC, mattruggio commented
LGTM

2021-08-12 03:43 UTC, mattruggio approved these changes
LGTM

2021-08-12 18:50 UTC, merged